### ISSUE TITLE
MC内发送的消息无法在群内发出

### ISSUE THREAD

**Issue by Tamamoimoto** [flben233/mc2qc_spigot#3]
[21:04:50 ERROR] [Minecraft]: Could not pass event AsyncPlayerChatEvent to mc2qc v1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.18.2-1.0.5-00ca124c.jar%2368!/:arclight-1.18.2-1.0.5-00ca124c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.18.2-1.0.5-00ca124c.jar%2368!/:arclight-1.18.2-1.0.5-00ca124c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.18.2-1.0.5-00ca124c.jar%2368!/:arclight-1.18.2-1.0.5-00ca124c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerPlayNetHandlerMixin.java:2497) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerPlayNetHandlerMixin.java:2448) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerPlayNetHandlerMixin.java:2423) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.md19b4d1$lambda$arclight$asyncChat$0$0(CChatMessagePacketMixin.java:528) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.SocketException: 你的主机中的软件中止了一个已建立的连接。
        at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
        at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
        at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
        at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
        at java.io.DataOutputStream.write(DataOutputStream.java:112) ~[?:?]
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:404) ~[?:?]
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[?:?]
        at mc2qc.Process.onChat(Process.java:44) ~[?:?]
        ... 12 more
[21:04:50 INFO] [Console]: <Tamamoimoto> 321

**Comment by flben233** [comment]
能否提供下所使用的服务端核心文件？明天我测试下看看

**Comment by Tamamoimoto** [comment]
用的是这个,https://github.com/IzzelAliz/Arclight/releases/tag/1.18%2F1.0.5

**Comment by Tamamoimoto** [comment]
> 能否提供下所使用的服务端核心文件？明天我测试下看看

用的是这个,https://github.com/IzzelAliz/Arclight/releases/tag/1.18%2F1.0.5

**Comment by flben233** [comment]
请检查arclight端mc2qc配置文件中token是否与mirai端mc2qc一致，如果不一致会导致这个问题。一般来说，如果token不一致，mirai控制台会输出"【mc2qc】密码错误，连接即将断开"，此后机器人将不再与服务器建立连接
